# Generated by Django 3.0.3 on 2020-03-01 11:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=3)),
                ('min_count', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('currency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                               related_name='currency_wallets', to='billing.Currency')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_wallets',
                                            to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('amount', models.FloatField()),
                ('wallet_from',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buy_transactions',
                                   to='billing.Wallet')),
                ('wallet_to',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sell_transactions',
                                   to='billing.Wallet')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CurrencyRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.FloatField()),
                ('currency_from',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates_to',
                                   to='billing.Currency')),
                ('currency_to',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates_from',
                                   to='billing.Currency')),
            ],
        ),
    ]
