# Generated by Django 3.0.3 on 2020-03-01 11:48

from django.db import migrations

from exn_tst_billing import settings


def init_main_currencies(apps, schema_editor):
    Currency = apps.get_model('billing', 'Currency')
    for code in ('USD', 'CNY', 'EUR'):
        currency = Currency(code=code)
        currency.save()


def init_super_user_with_wallet(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    main_user = User(username=settings.MAIN_USER_OWNER_USERNAME, is_staff=True)
    main_user.save()

    Currency = apps.get_model('billing', 'Currency')
    usd_currency = Currency.objects.get(code='USD')

    Wallet = apps.get_model('billing', 'Wallet')
    wallet = Wallet(currency=usd_currency, owner=main_user, amount=settings.INITIAL_MAIN_WALLET_AMOUNT)
    wallet.save()


class Migration(migrations.Migration):
    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(init_main_currencies),
        migrations.RunPython(init_super_user_with_wallet)
    ]
